keys:
  # Users
  - &users: # nix-shell -p age --run 'age-keygen'
    - &badele age15js628ku59g94njn0vup20r4xx34guesgsj5dqsken5hma2zqg2szjed66
  # Hosts
  - &hosts: # inv ssh-init-host-key
    - &rpi40 age152ud7upe5xylsvf7kkfpdz6x99r6hcmkam8gwntfdv0px70f0u0sqzc8qe 
    - &latino age12lhx7ktnd4fvqjeq06h0z25n0s0a3r0ap6thzsxwuxvglqsjufls8mhk9u
    - &sam age1x363tjjzx6j77j3m4zynkjgyj38qcyf4wah5mc8mtjt5yt6zvgxqr3z7px
    - &bootstore age1ejza6f2xzycq7jj2eu8fyg5vjdctljttm67mfteyd4k7wzvdyc8s7sc8jh
    - &badxps age1w9v05mvydywp39cq8tmgxjh8yc2w86qpp9aa4zt9ukf0qq8n5y4s5tkn7z

creation_rules:
  - path_regex: users/badele/secrets.yml$
    key_groups:
      - age:
          - *badele
          - *badxps

  - path_regex: hosts/secrets.yml$
    key_groups:
      - age:
          - *badele
          - *bootstore
          - *rpi40
          - *sam
          - *badxps

  - path_regex: hosts/rpi40/secrets.yml$
    key_groups:
      - age:
          - *badele
          - *rpi40

  - path_regex: hosts/bootstore/secrets.yml$
    key_groups:
      - age:
          - *badele
          - *bootstore

  - path_regex: hosts/latino.yml$
    key_groups:
      - age:
          - *badele
          - *latino

  - path_regex: hosts/sam.yml$
    key_groups:
      - age:
          - *badele
          - *sam

  - path_regex: hosts/badxps/secrets.yml$
    key_groups:
      - age:
          - *badele
          - *badxps