keys:
  # Users
  - &users: # nix-shell -p age --run 'age-keygen'
    - &badele age15js628ku59g94njn0vup20r4xx34guesgsj5dqsken5hma2zqg2szjed66
  # Hosts
  - &hosts: # nix-shell -p ssh-to-age --run 'cat hosts/<hostname>/ssh_host_ed25519_key.pub | ssh-to-age'
    - &rpi40 age152ud7upe5xylsvf7kkfpdz6x99r6hcmkam8gwntfdv0px70f0u0sqzc8qe 
    - &latino age12lhx7ktnd4fvqjeq06h0z25n0s0a3r0ap6thzsxwuxvglqsjufls8mhk9u
    - &bootstore age13rk87hygt7yc2p5tdwklt0yegh96cr6xs7cd0nluna5camscleaqztv47z

creation_rules:
  - path_regex: hosts/secrets.yml$
    key_groups:
      - age:
          - *badele
          - *rpi40
  - path_regex: hosts/rpi40/secrets.yml$
    key_groups:
      - age:
          - *badele
          - *rpi40
  - path_regex: hosts/bootstore/secrets.yml$
    key_groups:
      - age:
          - *badele
          - *bootstore
  - path_regex: hosts/latino.yml$
    key_groups:
      - age:
          - *badele
          - *latino